#%RAML 1.0
title: Entity Logo.

types:
  logo:
    type: object
    properties:
      id:
        type: string
        description: |
          Logo identifier.
        required: false
      name:
        type: string
        description: |
          Logo name.
        required: false
      url:
        type: string
        description: |
          Absolute url of the logo.
        required: false
