#%RAML 1.0
title: Entity ServiceProvider.

uses:
  logo: logo.raml
  amount: amount.raml

types:
  serviceProvider:
    type: object
    properties:
      id:
        type: string
        description: |
          Service provider identifier.
        required: false
      name:
        type: string
        description: |
          Service provider name.
        required: false
      logo:
        type: logo.logo
        description:
          Service provide logo.
        required: false
      possibleAmounts:
        type: amount.amount[]
        description: |
          Possible amounts
        required: false
